# - repo: wesQ3/vim-windowswap
- repo: habamax/vim-asciidoctor
  on_ft: adoc
  hook_add: |
    let g:asciidoctor_extensions = ['asciidoctor-diagram']
# - repo: padawan-php/deoplete-padawan
- repo: iamcco/markdown-preview.nvim
  on_ft: ['markdown', 'pandoc.markdown', 'rmd']
# - repo: scrooloose/vim-slumlord
#   on_ft: puml
- repo: aklt/plantuml-syntax
  # on_ft: puml
- repo: weirongxu/plantuml-previewer.vim
  on_ft: puml
- repo: jceb/vim-orgmode
  on_ft: org
  hook_add: |
    let g:org_export_emacs = "/usr/local/bin/emacs"
- repo: easymotion/vim-easymotion
  on_map: { n: <Plug> }
  hook_source: |
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to → '
    let g:EasyMotion_keys = 'fjdksweoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1
### Plugin: Easymotion

# Key   | Mode | Action
# ----- |:----:| ------------------
# `s`+`s` | Normal | Jump to two characters from input
# `s`+`d` | Normal | Jump to a character from input
# `s`+`f` | Normal | Jump over-windows
# `s`+`h` | Normal | Jump backwards in-line
# `s`+`l` | Normal | Jump forwards in-line
# `s`+`j` | Normal | Jump downwards
# `s`+`k` | Normal | Jump upwards
# `s`+`/` | Normal/operator | Jump to free-search
# `s`+`n` | Normal | Smart next occurrence
# `s`+`p` | Normal | Smart previous occurrence
